name = "AllocationViewer"
uuid = "e68bee48-ccd2-4290-be16-570446adc5cc"
version = "0.1.0"
authors = ["matthias314"]

[deps]
FoldingTrees = "1eca21be-9b9b-4ed8-839a-6d8ae26b1781"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
StructEqualHash = "8bd03d06-bfef-4aaf-8250-1a26cbb401bf"
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"

[compat]
FoldingTrees = "1.2"
InteractiveUtils = "1.11"
Profile = "1.11"
REPL = "1.11"
StructEqualHash = "0.1"
StyledStrings = "1.11"
julia = "1.12"
